DROP DATABASE IF EXISTS employee_db;
CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);

CREATE TABLE `role` (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  salary DECIMAL NOT NULL,
  department_id INT NOT NULL FOREIGN KEY REFERENCES department(id)
);

CREATE TABLE `role` (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  salary DECIMAL NOT NULL,
  department_id INT NOT NULL FOREIGN KEY REFERENCES department(id)
);
